version: "3.9"

services:
  app:
    build: .
    container_name: ticket_app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DB_PATH=/app/data/app.db
    restart: always